import os

# Do not change DEFAULT_CONFIG unless you know what you are doing
DEFAULT_CONFIG = {
    "url": "",
    "api_key": "",
    "games_bucket":"game-saves",
    "table_name":"saves-data"
}
CONFIG_FILE = 'config.json'
GAMES_FILE = 'games.json'

SKIP_EXTENSIONS = ['.tmp'] # Files with these extensions will be skipped during uploads e.g ['.tmp', '.log']
SKIP_GAMES = [] # Games with these names will be ignored by auto.py e.g ['Cuphead', 'Wolfenstein']
APP_NAME = 'Cloud Saves' # App name that shows up in notifications
ICON_PATH = os.path.join(os.path.dirname(__file__), APP_NAME) # Icon that shows up in notifications
POLL_INTERVAL = 2 # How many seconds between each check of running processes if auto.py running
LOG_FILE_NAME = 'cloud_saves.log' # Log file name generated by auto.py
LOG_FOLDER = 'Logs' # Folder to store logs in, keep empty if you want logs to be in working directory
MAX_LOG_BYTES = 5 * 1024 * 1024 # A new log file will be created once the current one reaches this file size (default 5 MB)
LOG_BACKUP_COUNT = 3 # How many old log files to keep
TRASH_FOLDER = 'Trash' # Folder to store deleted save files in
MAX_BACKUPS = 5 # Maximum number of save file backups to keep in the trash folder
CLEAR_TRASH = True # Whether to clear trash on each run of auto.py if MAX_BACKUPS is exceeded
SEND_NOTIFICATIONS = True # Whether auto.py sends notifications for important events
MAX_DOWNLOAD_THREADS = 4 # Higher = faster downloads but higher chance for failiure
MAX_UPLOAD_THREADS = 1 # Higher max_threads = faster uploads but higher chance for failiure